### ISSUE TITLE
__resolve_ckpt_dir does not work with ddp

### ISSUE THREAD

**Issue by JohannesK14** [tshu-w/lightning-template#1]
Hi @tshu-w ,

at first, thank you very much for providing and maintaining this repo!

I just noticed, that the `__resolve_ckpt_dir` function brakes when used in conjunction with ddp.

I am on c65989fcc32ee1d9e41b1f0f84a16782a660bd17 and created the environment with:

`mamba env create -n lt -f environment.yaml` and just tried:

`./run fit -c ./configs/mnist.yaml -c ./configs/presets/ddp.yaml -c ./configs/presets/debugger.yaml`

**Error message**
```
...
  File "/home/jwkuenzel/miniconda3/envs/lt/lib/python3.10/site-packages/lightning/pytorch/trainer/call.py", line 190, in _call_callback_hooks
    fn(trainer, trainer.lightning_module, *args, **kwargs)
  File "/home/jwkuenzel/miniconda3/envs/lt/lib/python3.10/site-packages/lightning/pytorch/callbacks/model_checkpoint.py", line 257, in setup
    dirpath = self.__resolve_ckpt_dir(trainer)
  File "/home/jwkuenzel/projects/lightning-template/src/utils/loggers.py", line 33, in __resolve_ckpt_dir
    ckpt_path = os.path.join(trainer.log_dir, "checkpoints")
  File "/home/jwkuenzel/miniconda3/envs/lt/lib/python3.10/posixpath.py", line 76, in join
    a = os.fspath(a)
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not NoneType
TypeError: expected str, bytes or os.PathLike object, not NoneType
    a = os.fspath(a)
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not NoneType
TypeError: expected str, bytes or os.PathLike object, not NoneType
```

**Comment by tshu-w** [comment]
Confirmed this issue. It did not occur when I was using Lightning 1.9.x. I will check and resolve the problem as soon as possible ;)

For your reference, the HACK of `__resolve_ckpt_dir` is to solve this issue https://github.com/Lightning-AI/lightning/issues/14188. I also tried to provide a PR https://github.com/Lightning-AI/lightning/pull/14640, but it is currently in pending status.

I'm glad you found this repo and gave it a try. After all, my README and tests are not very complete.

**Comment by JohannesK14** [comment]
Thank you very much!

I would love to see https://github.com/Lightning-AI/lightning/pull/14640 being merged into lightning. I think this would be a valuable addition.

Originally, I found your repo while browsing the pl issues, because I tried to integrate wandb into my workflow. I just saw that you removed wandb. May I ask you why?

**Comment by tshu-w** [comment]
I have been using wandb before, which is also very convenient. However, I found that the webpage would be a bit slow when there are many experiments. Recently, I want to try using [AimStack](https://aimstack.io) as a replacement.

If you want to use Wandb in my Template, you need to add the `log_dir` property to the `WandbLogger`. I accidentally deleted the history while merging branches.

```python
@property
def WandbLogger_log_dir(self) -> str:
    if hasattr(self, "_log_dir"):
        return self._log_dir

    save_dir = self._save_dir
    name = self.experiment.name
    version = self.experiment.id
    if all(isinstance(x, str) for x in (save_dir, name, version)):
        self._log_dir = os.path.join(save_dir, name, version)
        return self._log_dir


WandbLogger.log_dir = WandbLogger_log_dir
```

**Comment by tshu-w** [comment]
It should be fixed by https://github.com/tshu-w/lightning-template/commit/d9cb3208f36c043ae73d24b57d9c3a05a93b8663

**Comment by JohannesK14** [comment]
Works! Thanks!
